### PR TITLE
MBS-9255: Make aiprompt and marksheme prompt required

### PR DESCRIPTION
**Pull request by PM84**
It makes perfect sense to assume that the input fields aiprompt and markscheme are required.

### CODE REVIEW

**Comment by marcusgreen** [comment]
You are right that aiprompt should be required, that was something I overlooked. However I do not think markscheme should be required because there will be people who do not want to use it at all (i.e. feedback by an AI is one thing but a mark is a step further). Additionally getting marking right can be a significant challenge, as I found out today when experimenting with a math problem. I was thinking of making the mark scheme to be hide able on a global level via settings.

**Comment by marcusgreen** [comment]
Or perhaps I could make mark scheme to be required or not required based on a plugin settings switch?

**Comment by PM84** [comment]
You're right... I will remove the markesheme requirement.

**Comment by marcusgreen** [comment]
Excllent

**Review by marcusgreen — APPROVED** [review]

**Pull request merged**
